name: CloseIssuesWithMatchingFiles

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 运行一次
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run script to close issues
        env:
          ACCESS_TOKEN: "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"
          REPO_OWNER: "User-Howard"
          REPO_NAME: "Howard-OJ"
        run: |
          ls
