name: CloseIssuesWithMatchingFiles

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 运行一次
    
  workflow_dispatch:

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run script to close issues
        env:
          ACCESS_TOKEN: "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"
          REPO_OWNER: "User-Howard"
          REPO_NAME: "Howard-OJ"
        run: |
          ISSUES=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues?state=open")
          for row in $(echo "${ISSUES}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            ISSUE_TITLE=$(_jq '.title')
            ISSUE_NUMBER=$(_jq '.number')

            # 检查标题中是否包含 DELETEME
            if [[ "$ISSUE_TITLE" == *"DELETEME"* ]]; then
              # 删除问题
              curl -X DELETE -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER"
              echo "Deleted issue: $ISSUE_TITLE"
            fi
          done
