name: CloseIssuesWithMatchingFiles

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 运行一次
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run script to close issues
        env:
          ACCESS_TOKEN: "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"
          REPO_OWNER: "User-Howard"
          REPO_NAME: "Howard-OJ"
        run: |
         ISSUES=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues")
          for row in $(echo "${ISSUES}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            ISSUE_TITLE=$(_jq '.title')
            
            FILENAME=$(echo "$ISSUE_TITLE" | awk -F']' '{print $1}' | sed 's/\[//g' | sed 's/\//_/g' | tr '[:upper:]' '[:lower:]' | sed 's/ /_/g' | sed 's/_$//').cpp
            echo "Checking for file: $ISSUE_TITLE"
            if curl -s -o /dev/null -I -w "%{http_code}" -H "Authorization: token $ACCESS_TOKEN" "https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/main/$FILENAME" | grep -q 200; then
              ISSUE_NUMBER=$(_jq '.number')
              curl -s -X PATCH -H "Authorization: token $ACCESS_TOKEN" -d '{"state":"closed"}' "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER"
              echo "Closed issue: $ISSUE_TITLE"
            else
              echo "File not found: $FILENAME"
            fi
          done
