name: Process Issue Title

on:
  issues:
    types: [opened]
  workflow_dispatch:
jobs:
  process_title:
    runs-on: ubuntu-latest
    steps:
    - name: Extract folder path and file name
      id: extract_input
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const payload = context.payload;
          const labels = payload.issue.labels.map(label => label.name);
          if (labels.includes('want to solve')) {
            const title = payload.issue.title;
            const folder_path = title.match(/\[(.*?)\]/)[1];
            const file_name = title.split(' ')[1];
            console.log(`folder_path = ${folder_path}`);
            console.log(`file_name = ${file_name}`);
            console.log(`issue_number = ${payload.issue.number}`);
            core.setOutput('folder_path', folder_path);
            core.setOutput('file_name', file_name);
            core.setOutput('issue_number', payload.issue.number);
            
            // Call Python script to generate URL
            const { execSync } = require('child_process');
            const url = execSync(`python .github/scripts/generate_url.py "${title}"`, { encoding: 'utf-8' });
            console.log("Generated URL:", url.trim());
            
            // Reply to the issue
            const message = `**Judge:** ${folder_path}\n**Question Name:** *${file_name}*`;
            github.issues.createComment({
              owner: payload.repository.owner.login,
              repo: payload.repository.name,
              issue_number: payload.issue.number,
              body: message
            });
          }
