name: Process Issue Title

on:
  issues:
    types: [opened]
  workflow_dispatch:
jobs:
  process_title:
    runs-on: ubuntu-latest
    steps:
    - name: Extract folder path and file name
      id: extract_input
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          input="${{ github.event.issue.title }}"
          folder_path=$(echo "$input" | grep -o '\[.*\]' | tr -d '[]')
          file_name=$(echo "$input" | awk '{print $2}')
          echo "::set-output name=folder_path::$folder_path"
          echo "::set-output name=file_name::$file_name"
          echo "::set-output name=issue_number::${{ github.event.issue.number }}"

    - name: Reply to issue with extracted data
      if: steps.extract_input.outputs.folder_path != '' && steps.extract_input.outputs.file_name != ''
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = ${{ steps.extract_input.outputs.issue_number }};
          const folder_path = ${{ steps.extract_input.outputs.folder_path }};
          const file_name = ${{ steps.extract_input.outputs.file_name }};
          const message = `folder_path = ${folder_path}\nfile_name = ${file_name}`;
          github.issues.createComment({
            issue_number: issue_number,
            body: message
          });
